apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hr-app
  namespace: hr
  annotations:
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - host: hr.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hr-app
                port:
                  number: 80