apiVersion: v1
kind: Secret
metadata:
  name: hr-app-secret
  namespace: hr
type: Opaque
stringData:
  KEYCLOAK_CLIENT_SECRET: "5w6i1qzmctX5akPYBl0PEjSbqoiGMQNA"
  FLASK_SECRET_KEY: "kgC7sh88PgXp58Nw3Pe1Xy1dllc1Tqtpkem1ZA/Gp5Y="
  DB_PASSWORD: "password"
