apiVersion: v1
kind: Secret
metadata:
  name: hr-app-secret
  namespace: hr
type: Opaque
stringData:
  KEYCLOAK_CLIENT_SECRET: "change-me"
  FLASK_SECRET_KEY: "change-me-too"
  DB_PASSWORD: "super-secret-password"
